apiVersion: v1                          # API version for core Kubernetes objects like Service
kind: Service                           # Declares this resource as a Service
metadata:
  name: healthcare-backend-service      # The name of the Service

spec:
  selector:
    app: healthcare-backend             # Matches pods with this label to route traffic to them

  type: NodePort                        # Exposes the Service on each node's IP at a static port (NodePort)

  ports:
    - protocol: TCP                     # Protocol used (commonly TCP for web applications)
      port: 8082                        # Port that the Service exposes internally within the cluster
      targetPort: 8082                  # Port on the container to forward traffic to
      nodePort: 30082                   # Port exposed on each Node’s IP — accessible from outside the cluster
                                        # Access format: http://<Node-IP>:30082
